# tasks file for rstudio-server
---
- name: install | dependencies
  apt:
    name: "{{ rstudio_server_dependencies }}"
    state: "{{ apt_install_state | default('latest') }}"
    update_cache: true
    cache_valid_time: "{{ apt_update_cache_valid_time | default(3600) }}"
  tags:
    - rstudio-server-install-dependencies

- name: install | additional
  apt:
    name: "{{ rstudio_server_install }}"
    state: "{{ apt_install_state | default('latest') }}"
  tags:
    - rstudio-server-install-additional

- name: install | create (download) directory
  file:
    path: "{{ rstudio_server_downloads_path }}"
    state: directory
    owner: root
    group: root
    mode: 0755
  tags:
    - rstudio-server-install-download
    - rstudio-server-install-download-directory

- name: install | download deb
  command: >
    curl --silent --show-error --fail --location
    {{ rstudio_server_download_url }}
    -o {{ rstudio_server_downloads_path }}/rstudio-server-{{ rstudio_server_version }}-{{ rstudio_server_machine_map[ansible_machine] }}.deb
  args:
    creates: "{{ rstudio_server_downloads_path }}/rstudio-server-{{ rstudio_server_version }}-{{ rstudio_server_machine_map[ansible_machine] }}.deb"
    warn: false
  tags:
    - rstudio-server-install-download
    - rstudio-server-install-download-deb

- name: install | install deb
  apt:
    deb: "{{ rstudio_server_downloads_path }}/rstudio-server-{{ rstudio_server_version }}-{{ rstudio_server_machine_map[ansible_machine] }}.deb"
  tags:
    - rstudio-server-install-install
    - rstudio-server-install-install-deb
