# tasks file for rstudio-server
---
- include: install.yml
  tags:
   - configuration
   - rstudio-server
   - rstudio-server-install

- include: configure.yml
  tags:
   - configuration
   - rstudio-server
   - rstudio-server-configure

- name: start and enable service
  service:
    name: rstudio-server
    state: started
    enabled: true
  tags:
    - configuration
    - rstudio-server
    - rstudio-server-start-enable-service
