# tasks file for rstudio-server
---
- name: include variables
  include_vars: "{{ item }}"
  with_first_found:
    - "_{{ ansible_distribution_release }}.yml"
    - "_{{ ansible_distribution | lower }}.yml"
    - _default.yml
  tags:
   - configuration
   - rstudio-server
   - - rstudio-server-include-variables

- include: install.yml
  tags:
   - configuration
   - rstudio-server
   - rstudio-server-install

- include: configure.yml
  tags:
   - configuration
   - rstudio-server
   - rstudio-server-configure

- name: start and enable service
  service:
    name: rstudio-server
    state: "{{ service_default_state | default('started') }}"
    enabled: "{{ service_default_enabled | default(true) | bool }}"
  tags:
    - configuration
    - rstudio-server
    - rstudio-server-start-enable-service
