# tasks file for rstudio-server
---
- include: install.yml
  tags:
   - configuration
   - rstudio-server
   - rstudio-server-install

- include: configure.yml
  tags:
   - configuration
   - rstudio-server
   - rstudio-server-configure

- name: start and enable service
  service:
    name: rstudio-server
    state: "{{ service_default_state | default('started') }}"
    enabled: "{{ service_default_enabled | default(true) | bool }}"
  tags:
    - configuration
    - rstudio-server
    - rstudio-server-start-enable-service
